name: 'Build'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode'
      - 'assets'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20']
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        # arch: ['amd64', 'arm64']
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: '--max_old_space_size=16384'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Compile Electron app
        run: |
          npm run build
          npm run package
          mkdir -p pkg
          tar cjvf pkg/`ls out`.tar.gz -C ./out ./`ls out`

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          # name: maa-y-${{ matrix.os }}-${{ matrix.arch }}
          name: maa-y-${{ matrix.os }}
          path: 'pkg'
