name: 'Build'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode'
      - 'assets'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20']
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        # arch: ['amd64', 'arm64']
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: '--max_old_space_size=16384'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Download MaaAgentBinary
        run: git clone https://github.com/MaaAssistantArknights/MaaAgentBinary.git --depth=1

      - name: Install dependencies
        run: pnpm i

      - name: Compile Electron app
        run: |
          pnpm run build
          pnpm run package
          mkdir -p pkg
          cp -r MaaAgentBinary ./out/`ls out`/
          cp -r assets ./out/`ls out`/
          mkdir ./out/`ls out`/maa
          touch "./out/`ls out`/maa/PUT_MaaRpcCli_HERE"
          cp initcfg.json ./out/`ls out`/config.json
          tar cjvf pkg/`ls out`.tar.gz -C ./out ./`ls out`

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          # name: maa-y-${{ matrix.os }}-${{ matrix.arch }}
          name: maa-y-${{ matrix.os }}
          path: 'pkg'
