name: 'Respack'

on:
  push:
    paths:
      - '.github/workflows/respack.yml'
      - 'respack/**'
      - 'scripts/**'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup assets
        run: |
          node scripts/makeRespack.mjs
          mkdir res
          tar cjvfh res/assets.tar.gz ./assets

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: maa-y-assets
          path: 'res'
